---
title: "Single marker GWAS"
author: "Gota Morota"
date: "March 25, 2020"
output: 
    prettydoc::html_pretty:
      theme: architect
      highlight: vignette
      toc: true
---


```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```


This example illustrates how to perform single-marker GWAS using the [rrBLUP](https://cran.r-project.org/web/packages/rrBLUP/index.html) R package. 

## Data 
We will use the maize data available in the [synbreedData](https://rdrr.io/cran/synbreedData/) R package. 
```{r, eval=FALSE}
rm(list=ls())
library(synbreedData)
data(maize)
?maize
names(maize)
y <- data.frame(ID=rownames(maize$pheno), pheno = maize$pheno[,1,1])
W <- maize$geno
W[W==0] = -1 # convert 0 to -1
map <- maize$map
```


# Single-marker GWAS
```{r, eval=FALSE}
# install.packages("rrBLUP")
library(rrBLUP)
my.geno <- data.frame(marker=rownames(map), chrom=map[,1], pos=map[,2], t(W), check.names = FALSE) 
my.geno[1:5, 1:10] # display the frist 5 rows and 10 columns 
?GWAS
fit <-  GWAS(y, my.geno, min.MAF=0.05, P3D=TRUE, plot=FALSE)
head(fit)
```

# Manhattan plot
```{r eval=FALSE, echo=TRUE}
# install.packages("qqman")
library(qqman)
manhattan(x = fit, chr = "chrom", bp = "pos", p = "pheno", snp = "marker", col = c("blue4", "orange3"), logp = FALSE)
```

