---
title: "Ridge regression BLUP (RRBLUP)"
author: "Gota Morota"
date: "March 25, 2020"
output: 
    prettydoc::html_pretty:
      theme: architect
      highlight: vignette
      toc: true
---


```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```


This example illustrates how to fit ridge regression BLUP using the [rrBLUP](https://cran.r-project.org/web/packages/rrBLUP/index.html) R package. 

## Data 
We will use the maize data available in the [synbreedData](https://rdrr.io/cran/synbreedData/) R package. 
```{r, eval=FALSE}
rm(list=ls())
library(synbreedData)
data(maize)
?maize
names(maize)
y <-maize$pheno[,1,1]
W <- maize$geno
W[W==0] = -1 # convert 0 to -1
map <- maize$map
```


# Ridge regression BLUP
The `mixed.solve()` function implements ridge regression BLUP. 
```{r, eval=FALSE}
# install.packages("rrBLUP")
library(rrBLUP)
?mixed.solve
fit <-  mixed.solve(y = y, Z = W)
```

# Results
```{r eval=FALSE, echo=TRUE}
fit$beta # intercept

head(fit$u) # marker effects

fit$Vu # marker genetic variance

fit$Ve # residual variance

fit$Ve / fit$Vu # lambda
```

