---
title: "Genomic best linear unbiased prediction "
author: "Gota Morota"
date: "March 2, 2020"
output: 
    prettydoc::html_pretty:
      theme: architect
      highlight: vignette
      toc: true
---


```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```


## Data 
```{r}
library(BGLR)
data(mice)
y <- mice.pheno$Obesity.BMI 
W0 <- mice.X 
dim(W0)

p <- colSums(W0)/(2 * nrow(W0))
maf <- ifelse(p > 0.5, 1 - p, p)  # or pmin(p, 1-p)
maf.index <- which(maf < 0.1)
p0 <- p[-maf.index]
W0 <- W0[, -maf.index]
dim(W0)
```


## Genomic relationship matrix
```{r}
W <- scale(W0, center = TRUE, scale = FALSE)
G <- tcrossprod(W) / sum(2*p0*(1-p0))
```


## Genomic best linear unbiased prediction
```{r}
sigma2g <- 0.0007119091
sigma2e <- 0.002941943
  
I <- diag(nrow(G)) # diagonal matrix
Ginv <- solve(G) # inverse of G
ghat <- solve(I + Ginv * (sigma2e/sigma2g))  %*% matrix(y) # GBLUP

head(ghat)
tail(ghat)
```




