---
title: "Genomic relationship matrix"
author: "Gota Morota"
date: "February 24, 2020"
output: 
    prettydoc::html_pretty:
      theme: architect
      highlight: vignette
      toc: true
---


```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```


## Data 
```{r}
library(BGLR)
data(mice)
W <- mice.X 
dim(W)

p <- colSums(W)/(2 * nrow(W))
maf <- ifelse(p > 0.5, 1 - p, p)  # or pmin(p, 1-p)
maf.index <- which(maf < 0.1)
p2 <- p[-maf.index]
W2 <- W[, -maf.index]
dim(W2)
```


## VanRaden Method 1
```{r}
W3 <- scale(W2, center = TRUE, scale = FALSE)
G1 <- tcrossprod(W3) / sum(2*p*(1-p))

# Genomic relationship between individuals 1 and 5
G1[1,5]

# Genomic relationship between individuals 1 and 10
G1[1,10]
```


## VanRaden Method 2
```{r}
Wcs <- scale(W2, center = TRUE, scale = TRUE)
G2 <- tcrossprod(Wcs)/ncol(Wcs)

# Genomic relationship between individuals 1 and 5
G2[1,5]

# Genomic relationship between individuals 1 and 10
G2[1,10]

# Cor between G1 and G2
cor(G1[upper.tri(G1)], G2[upper.tri(G2)])
```





